# chunk:
#   size: 1000
#   overlap: 500
# embedding:
#   model: "models\\all-MiniLM-L6-v2"
# faiss:
#   index_path: embeddings/faiss_index
# llm:
#   model: llama3
#   mode: ollama
# relevance_model:
#   path: models/relevance_model.pkl
# cache:
#   db_path: cache/query_cache.db
# source_dir: data/raw_pdfs
# chunks_dir: data/chunks
# cleaned_texts_dir: data/cleaned_texts
# metadata_dir: data/metadata

chunk:
 size: 1000
 overlap: 500
embedding:
 model: "models\\all-MiniLM-L6-v2"
faiss:
 index_path: embeddings/{product}/faiss_index
llm:
 model: llama3
 mode: ollama
relevance_model:
 path: models/relevance_model.pkl
cache:
 db_path: cache/query_cache.db
base_data_dir: data
base_embeddings_dir: embeddings



